name       : hunspell-ru
version    : 20131101
release    : 1
source     :
    - https://bitbucket.org/Shaman_Alex/russian-dictionary-hunspell/downloads/ru_RU_UTF-8_20131101.zip : c9c30ca305705691fea4810137763f3b790676aa534a5cd6dfc9b45659aa9408
license    : LGPL-3.0
component  : spelling
summary    : Russian hunspell dictionaries
description: |
    Russian hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 ru_RU.dic $installdir/usr/share/hunspell
    install -m 00644 ru_RU.aff $installdir/usr/share/hunspell